#!/usr/bin/env python3
# ------------------------------------------------------------------
# gain_codebook_generator.py - Train the 2-D gain codebook (cl. 4.2.2.6)
#
# Usage:
#   python3 gain_codebook_generator.py [--clip-lo LO] [--clip-hi HI] \
#       features.txt > src/gain_codebook.c
#
# The features file contains one "(err_pit, err_cod)" pair per line,
# collected from the encoder built with -DGAIN_TRAINING:
#
#   make clean && make CFLAGS="-Wall -Wextra -O2 -std=c99 -DGAIN_TRAINING"
#   ./openacelp speech.raw 2> features.txt
#
# The script runs the Linde-Buzo-Gray (LBG) algorithm to cluster the
# features into 64 2-D vectors (6 bits) and emits a C source file with
# the codebook table, in the natural float log2-energy scale used by
# src/gain.c (see docs/plan-4.2.2.6.md, decisions D1/D2).
#
# IMPORTANT: keep the quiet/silence frames in the training data. In the
# natural float scale their errors are very negative (down to log2 of the
# energy guard). If they are clipped away, the codebook cannot represent
# quiet frames and the gain reconstruction 2^(0.5*(cb+pred-e)) blows up.
# LBG allocates entries where the data density is, so keeping silence is
# what makes quiet frames reconstruct to ~zero gain. Optional --clip-lo/
# --clip-hi only remove absurd outliers (default: no clipping).
#
# A tiny pure-Python LBG is included so the script has no dependencies;
# it is the same algorithm as the py-lbg tool used for the LSP codebooks.
# ------------------------------------------------------------------

import math
import sys

CB_SIZE = 64  # codebook size (6 bits)
MAX_ITER = 200  # Lloyd iterations per split stage


def read_features(paths, clip_lo=None, clip_hi=None):
    """Read (err_pit, err_cod) lines from one or more feature files."""
    if isinstance(paths, str):
        paths = [paths]
    feats = []
    for path in paths:
        with open(path, "r") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                parts = line.split()
                if len(parts) < 2:
                    continue
                try:
                    x, y = float(parts[0]), float(parts[1])
                except ValueError:
                    continue
                if not (math.isfinite(x) and math.isfinite(y)):
                    continue
                if clip_lo is not None:
                    x = max(clip_lo, x)
                    y = max(clip_lo, y)
                if clip_hi is not None:
                    x = min(clip_hi, x)
                    y = min(clip_hi, y)
                feats.append((x, y))
    return feats


def centroid(points):
    n = len(points)
    if n == 0:
        return None
    sx = sum(p[0] for p in points)
    sy = sum(p[1] for p in points)
    return (sx / n, sy / n)


def dist2(a, b):
    dx = a[0] - b[0]
    dy = a[1] - b[1]
    return dx * dx + dy * dy


def lloyd(points, centers):
    """One assignment + centroid-update pass. Returns new centers."""
    cells = [[] for _ in centers]
    for p in points:
        best, bd = 0, dist2(p, centers[0])
        for i in range(1, len(centers)):
            d = dist2(p, centers[i])
            if d < bd:
                best, bd = i, d
        cells[best].append(p)

    new = []
    for i, cell in enumerate(cells):
        c = centroid(cell)
        if c is None:
            # Empty cell: keep the old center, slightly jittered
            c = (centers[i][0] + 0.01, centers[i][1] - 0.01)
        new.append(c)
    return new


def lbg(points, n):
    """Binary-splitting LBG. n must be a power of two."""
    centers = [centroid(points)]
    eps = 0.5

    while len(centers) < n:
        # Split every center into two
        split = []
        for x, y in centers:
            split.append((x + eps, y))
            split.append((x - eps, y))
        centers = split

        # Refine until convergence
        for _ in range(MAX_ITER):
            prev = centers
            centers = lloyd(points, centers)
            moved = max(dist2(centers[i], prev[i]) for i in range(len(centers)))
            if moved < 1e-6:
                break

    return centers[:n]


def emit_c(centers):
    print('#include "openacelp_internal.h"')
    print()
    print("//------------------------------------------------------------------")
    print("// Gain codebook data (cl. 4.2.2.6). See include/gain_codebook.h.")
    print("// Generated by scripts/gain_codebook_generator.py (LBG).")
    print("//------------------------------------------------------------------")
    print()
    print("const float gain_cb[GAIN_CB_SIZE][2] =")
    print("{")
    for i in range(0, len(centers), 4):
        row = []
        for c in centers[i : i + 4]:
            row.append("{%7.3f, %7.3f}" % c)
        print("\t" + ",  ".join(row) + ",")
    print("};")


def main():
    args = sys.argv[1:]
    clip_lo = None
    clip_hi = None
    while args and args[0].startswith("--"):
        if args[0] == "--clip-lo" and len(args) > 1:
            clip_lo = float(args[1])
            args = args[2:]
        elif args[0] == "--clip-hi" and len(args) > 1:
            clip_hi = float(args[1])
            args = args[2:]
        else:
            print("unknown option: %s" % args[0], file=sys.stderr)
            sys.exit(1)

    if len(args) < 1:
        print(
            "usage: %s [--clip-lo LO] [--clip-hi HI] features.txt [more.txt ...]"
            % sys.argv[0],
            file=sys.stderr,
        )
        sys.exit(1)

    feats = read_features(args, clip_lo, clip_hi)
    if len(feats) < CB_SIZE:
        print(
            "error: need at least %d feature vectors, got %d" % (CB_SIZE, len(feats)),
            file=sys.stderr,
        )
        sys.exit(1)

    centers = lbg(feats, CB_SIZE)
    emit_c(centers)


if __name__ == "__main__":
    main()
