#!/usr/bin/env python3
# ------------------------------------------------------------------
# gain_codebook_generator.py - Train the 2-D gain codebook (cl. 4.2.2.6)
#
# Usage:
#   python3 gain_codebook_generator.py [--clip-lo LO] [--clip-hi HI] \
#       [--max-points N] features.txt [more.txt ...] > src/gain_codebook.c
#
# The feature files contain one "(err_pit, err_cod)" pair per line,
# collected from the encoder built with -DGAIN_TRAINING:
#
#   make clean && make CFLAGS="-Wall -Wextra -O2 -std=c99 -DGAIN_TRAINING"
#   for f in raw/*.raw; do ./openacelp "$f" 2>> features.txt > /dev/null; done
#
# The script runs the Linde-Buzo-Gray (LBG) algorithm to cluster the
# features into 64 2-D vectors (6 bits) and emits a C source file with
# the codebook table, in the natural float log2-energy scale used by
# src/gain.c (see docs/codebook_training.md).
#
# IMPORTANT: keep the quiet/silence frames in the training data. In the
# natural float scale their errors are very negative (down to log2 of the
# energy guard). If they are clipped away, the codebook cannot represent
# quiet frames and the gain reconstruction 2^(0.5*(cb+pred-e)) blows up.
# LBG allocates entries where the data density is, so keeping silence is
# what makes quiet frames reconstruct to ~zero gain. Optional --clip-lo/
# --clip-hi only remove absurd outliers (default: no clipping).
#
# The LBG is vectorised with numpy and both the text parsing and the
# Lloyd iterations run in chunks, so it handles tens of millions of
# points with low memory: ~50 M points (100 h of speech) peak at
# roughly 1 GB RAM, well within any modern machine. --max-points
# optionally subsamples (not needed normally).
#
# Requires: numpy (python3 -m pip install numpy). The shared, vectorised
# LBG machinery (chunked text parsing, batched Lloyd iterations) lives in
# scripts/lbg_common.py.
# ------------------------------------------------------------------

import os
import sys

from lbg_common import read_features, lbg

CB_SIZE = 64  # codebook size (6 bits)
DIM = 2  # (err_pit, err_cod)


def emit_c(centers):
    print('#include "openacelp_internal.h"')
    print()
    print("//------------------------------------------------------------------")
    print("// Gain codebook data (cl. 4.2.2.6). See include/gain_codebook.h.")
    print("// Generated by scripts/gain_codebook_generator.py (LBG).")
    print("//------------------------------------------------------------------")
    print()
    print("const float gain_cb[GAIN_CB_SIZE][2] =")
    print("{")
    for i in range(0, len(centers), 4):
        row = []
        for k in range(i, min(i + 4, len(centers))):
            c = centers[k]
            row.append("{%7.3f, %7.3f}" % (float(c[0]), float(c[1])))
        print("\t" + ",  ".join(row) + ",")
    print("};")


def main():
    args = sys.argv[1:]
    clip_lo = None
    clip_hi = None
    max_points = None
    while args and args[0].startswith("--"):
        opt = args[0]
        if opt in ("--clip-lo", "--clip-hi", "--max-points") and len(args) > 1:
            val = args[1]
            if opt == "--clip-lo":
                clip_lo = float(val)
            elif opt == "--clip-hi":
                clip_hi = float(val)
            else:
                max_points = int(val)
            args = args[2:]
        else:
            print("unknown option: %s" % opt, file=sys.stderr)
            sys.exit(1)

    if len(args) < 1:
        print(
            "usage: %s [--clip-lo LO] [--clip-hi HI] [--max-points N] "
            "features.txt [more.txt ...]" % sys.argv[0],
            file=sys.stderr,
        )
        sys.exit(1)

    feats = read_features(args, DIM, clip_lo, clip_hi, max_points)
    if len(feats) < CB_SIZE:
        print(
            "error: need at least %d feature vectors, got %d" % (CB_SIZE, len(feats)),
            file=sys.stderr,
        )
        sys.exit(1)

    print(
        "LBG: %d feature vectors -> %d entries ..." % (len(feats), CB_SIZE),
        file=sys.stderr,
    )
    centers = lbg(feats, CB_SIZE)
    emit_c(centers)


if __name__ == "__main__":
    # make `from lbg_common import ...` work no matter the CWD
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    main()
