#!/usr/bin/env python3
# ------------------------------------------------------------------
# lsp_codebook_generator.py - Train the 3 LSP split-VQ codebooks
# (ETSI EN 300-395-2 cl. 4.2.2.3)
#
# Usage:
#   python3 lsp_codebook_generator.py [--eps E] [--max-points N] \
#       features.txt [more.txt ...] > include/LSP_codebooks.h
#
# Feature files: one LSP vector per line — 10 values in the cosine
# domain (q_k = cos(w_k), strictly decreasing), dumped by the encoder
# built with -DLSP_TRAINING:
#
#   make clean && make CFLAGS="-Wall -Wextra -O2 -std=c99 -DLSP_TRAINING"
#   for f in raw/*.raw; do ./openacelp "$f" 2>> lsp_features.txt > /dev/null; done
#
# The 10-D vectors are split into the 3 standard groups (3 + 3 + 4) and
# each group is clustered with the shared numpy LBG
# (scripts/lbg_common.py) into the standard codebook sizes:
#
#   codebook 1: 3-D  {q1,q2,q3}       256 entries (8 bits)
#   codebook 2: 3-D  {q4,q5,q6}       512 entries (9 bits)
#   codebook 3: 4-D  {q7..q10}        512 entries (9 bits)
#
# and the tables are emitted as include/LSP_codebooks.h (same layout as
# the original py-lbg trained tables, but written as static const).
#
# Data volume: these codebooks want much more data than the 64-entry
# gain codebook — tens of hours of speech (tens of millions of frames).
# The chunked LBG handles that in ~1 GB of RAM (see lbg_common.py).
#
# Requires: numpy.
# ------------------------------------------------------------------

import os
import sys

import numpy as np

from lbg_common import read_features, lbg

DIM = 10  # full LSP vector dimension

# (table name, start col, end col, codebook size)  — sizes are powers of two
GROUPS = [
    ("cb1", 0, 3, 256),
    ("cb2", 3, 6, 512),
    ("cb3", 6, 10, 512),
]


def emit_group(name, dim, size, centers):
    print("// %s: %d-D codebook, %d entries" % (name, dim, size))
    print("static const float %s[dim_%s*size_%s] =" % (name, name, name))
    print("{")
    for c in centers:
        print("\t" + ", ".join("%.9f" % float(v) for v in c) + ",")
    print("};")
    print()


def emit_header(centers_by_group):
    print("//------------------------------------------------------------------")
    print("// LSP codebooks: split vector quantization with 3 codebooks.")
    print("// The LSPs are in the cosine domain [-1, 1]. Refer to")
    print("// ETSI EN 300-395-2, chapter 4.2.2.3.")
    print("//")
    print("// Codebook\t\t  vector dimension\t\tnumber of vectors")
    print("//     1\t\t3 -   {q1, q2, q3}\t\t  256 (8 bits)")
    print("//     2\t\t3 -   {q4, q5, q6}\t\t  512 (9 bits)")
    print("//     3\t\t4 - {q7, q8, q9, q10}\t  512 (9 bits)")
    print("//")
    print("// Generated by scripts/lsp_codebook_generator.py (LBG) from")
    print("// encoder -DLSP_TRAINING output.")
    print("//------------------------------------------------------------------")
    print()
    print("#ifndef LSP_CODEBOOKS")
    print("#define LSP_CODEBOOKS")
    print()
    print("// Dimensions")
    print("#define dim_cb1\t\t3")
    print("#define dim_cb2\t\t3")
    print("#define dim_cb3\t\t4")
    print("// Sizes")
    print("#define size_cb1\t%d" % GROUPS[0][3])
    print("#define size_cb2\t%d" % GROUPS[1][3])
    print("#define size_cb3\t%d" % GROUPS[2][3])
    print()
    for name, start, end, size in GROUPS:
        emit_group(name, end - start, size, centers_by_group[name])
    print("#endif")
    print()


def valid_lsp_centers(centers, min_spacing=1e-4):
    """Make every codebook entry a *valid* LSP sub-vector: components
    clipped to [-1, 1] (cosine domain), sorted in descending order
    (LSPs are strictly decreasing: q1 > q2 > ... > q10) and separated by
    at least min_spacing. LBG on real data yields ordered, in-range
    centroids; this only cleans up the degenerate entries that empty
    cells can leave behind (a center with no assigned points keeps
    drifting by +-eps across split stages, which with a small training
    set can push it out of range — clipping then collides components on
    the same bound, e.g. [1.0, 1.0, 1.0])."""
    c = np.clip(centers, -1.0, 1.0)
    c = np.sort(c, axis=1)[:, ::-1]  # descending per entry
    for row in c:
        for i in range(1, row.shape[0]):
            if row[i] >= row[i - 1]:
                row[i] = max(-1.0, row[i - 1] - min_spacing)
    return c


def main():
    args = sys.argv[1:]
    eps = 0.05
    max_points = None
    while args and args[0].startswith("--"):
        opt = args[0]
        if opt in ("--eps", "--max-points") and len(args) > 1:
            val = args[1]
            if opt == "--eps":
                eps = float(val)
            else:
                max_points = int(val)
            args = args[2:]
        else:
            print("unknown option: %s" % opt, file=sys.stderr)
            sys.exit(1)

    if len(args) < 1:
        print(
            "usage: %s [--eps E] [--max-points N] features.txt [more.txt ...]"
            % sys.argv[0],
            file=sys.stderr,
        )
        sys.exit(1)

    feats = read_features(args, DIM, max_points=max_points)
    min_needed = max(size for _, _, _, size in GROUPS)
    if len(feats) < min_needed:
        print(
            "error: need at least %d feature vectors (frames), got %d"
            % (min_needed, len(feats)),
            file=sys.stderr,
        )
        sys.exit(1)

    centers_by_group = {}
    for name, start, end, size in GROUPS:
        print(
            "LBG %s: %d feature vectors -> %d entries (dim %d) ..."
            % (name, len(feats), size, end - start),
            file=sys.stderr,
        )
        centers_by_group[name] = valid_lsp_centers(
            lbg(feats[:, start:end], size, eps=eps)
        )

    emit_header(centers_by_group)


if __name__ == "__main__":
    # make `from lbg_common import ...` work no matter the CWD
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    main()
